In [1]:
import pandas as pd

from mlxtend.frequent_patterns import apriori

from mlxtend.frequent_patterns import association_rules
# df = pd.read_excel('Online_Retail.xlsx')
df = pd.read_csv('processed_data.csv')
df.head()

,Time,Cache_id,cache_time,no,cache_next,cache_occurance
0,2020-05-22 05:55:46.378307,2,1.0,0,2.0,1
1,2020-05-22 05:58:46.378307,16,181.0,1,32.0,1
2,2020-05-22 06:01:46.378307,2,361.0,2,4.0,2
3,2020-05-22 06:04:46.378307,20,541.0,3,138.0,1
4,2020-05-22 06:07:46.378307,2,721.0,4,5.0,3

In [4]:
dfn = df['Cache_id']
print(dfn.head())
print(len(dfn))

0     2
1    16
2     2
3    20
4     2
Name: Cache_id, dtype: int64
1902

In [15]:
h = {i:[] for i in range(1,21)}
#h['Cache_id'] = []
b = list(range(0,1900,10))
a = list(range(10,1901,10))
for i in range(len(a)):
    l_10 = dfn[b[i]:a[i]]
    #print(l_10)
    for j in h.keys():
        if j in list(l_10):
            #print('yes')
            h[j].append(1)
        else:
            #print(j, list(l_10))
            h[j].append(0)

In [17]:
new_df = pd.DataFrame.from_dict(h)

In [18]:
new_df

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0
2,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0
3,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0
4,1,1,1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,0,1,0,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1,0
186,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,0
187,0,1,1,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0
188,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
189,1,1,0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,0,0,0

In [ ]:
# df['Description'] = df['Description'].str.strip()
# df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
# df['InvoiceNo'] = df['InvoiceNo'].astype('str')

# df = df[~df['InvoiceNo'].str.contains('C')]

# df

In [ ]:
# only data for france and grouped by invoice description
# converting to one transaction per row
# basket = (df[df['Country'] =='France']
#           .groupby(['InvoiceNo', 'Description'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('InvoiceNo'))

# basket

In [ ]:
# def encode_units(x):
#     if x <= 0:
#         return 0
#     if x >= 1:
#         return 1
# basket_ssts = basket.applymap(encode_units)
# basket_sets.drop('POSTAGE', inplace=True, axis=1)
# basket_sets

In [20]:
frequent_itemsets = apriori(new_df, min_support=0.07, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
#rules.head()
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(1),(6),0.173684,0.389474,0.073684,0.424242,1.089271,0.006039,1.060388
1,(6),(1),0.389474,0.173684,0.073684,0.189189,1.089271,0.006039,1.019123
2,(1),(10),0.173684,0.305263,0.078947,0.454545,1.489028,0.025928,1.273684
3,(10),(1),0.305263,0.173684,0.078947,0.258621,1.489028,0.025928,1.114565
4,(2),(3),0.984211,0.736842,0.726316,0.737968,1.001528,0.001108,1.004296
...,...,...,...,...,...,...,...,...,...
487,"(5, 6)","(2, 3, 4)",0.173684,0.373684,0.073684,0.424242,1.135297,0.008781,1.087812
488,(2),"(3, 4, 5, 6)",0.984211,0.073684,0.073684,0.074866,1.016043,0.001163,1.001278
489,(4),"(2, 3, 5, 6)",0.563158,0.094737,0.073684,0.130841,1.381101,0.020332,1.041539
490,(5),"(2, 3, 4, 6)",0.447368,0.142105,0.073684,0.164706,1.159041,0.010111,1.027057
491,(6),"(2, 3, 4, 5)",0.389474,0.163158,0.073684,0.189189,1.159547,0.010139,1.032105

In [28]:
rules[ (rules['lift'] >= 1) &
(rules['confidence'] >= 1.) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(9),(2),0.189474,0.984211,0.189474,1.0,1.016043,0.002992,inf
11,(10),(2),0.305263,0.984211,0.305263,1.0,1.016043,0.004820,inf
12,(17),(2),0.178947,0.984211,0.178947,1.0,1.016043,0.002825,inf
15,(19),(2),0.163158,0.984211,0.163158,1.0,1.016043,0.002576,inf
68,"(1, 3)",(2),0.100000,0.984211,0.100000,1.0,1.016043,0.001579,inf
71,"(1, 10)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
76,"(3, 4)",(2),0.373684,0.984211,0.373684,1.0,1.016043,0.005900,inf
78,"(3, 7)",(2),0.215789,0.984211,0.215789,1.0,1.016043,0.003407,inf
81,"(9, 3)",(2),0.152632,0.984211,0.152632,1.0,1.016043,0.002410,inf
86,"(10, 3)",(2),0.205263,0.984211,0.205263,1.0,1.016043,0.003241,inf
93,"(3, 14)",(2),0.152632,0.984211,0.152632,1.0,1.016043,0.002410,inf
101,"(17, 3)",(2),0.136842,0.984211,0.136842,1.0,1.016043,0.002161,inf
110,"(3, 19)",(2),0.110526,0.984211,0.110526,1.0,1.016043,0.001745,inf
114,"(4, 5)",(2),0.263158,0.984211,0.263158,1.0,1.016043,0.004155,inf
127,"(9, 4)",(2),0.115789,0.984211,0.115789,1.0,1.016043,0.001828,inf
132,"(10, 4)",(2),0.152632,0.984211,0.152632,1.0,1.016043,0.002410,inf
136,"(4, 15)",(2),0.136842,0.984211,0.136842,1.0,1.016043,0.002161,inf
139,"(16, 4)",(2),0.131579,0.984211,0.131579,1.0,1.016043,0.002078,inf
144,"(17, 4)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
146,"(18, 4)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
150,"(19, 4)",(2),0.105263,0.984211,0.105263,1.0,1.016043,0.001662,inf
154,"(20, 4)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
156,"(5, 7)",(2),0.115789,0.984211,0.115789,1.0,1.016043,0.001828,inf
158,"(10, 5)",(2),0.121053,0.984211,0.121053,1.0,1.016043,0.001911,inf
160,"(5, 14)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
166,"(17, 5)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
177,"(10, 6)",(2),0.115789,0.984211,0.115789,1.0,1.016043,0.001828,inf
186,"(19, 6)",(2),0.089474,0.984211,0.089474,1.0,1.016043,0.001413,inf
196,"(10, 7)",(2),0.110526,0.984211,0.110526,1.0,1.016043,0.001745,inf
200,"(7, 15)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
204,"(18, 7)",(2),0.089474,0.984211,0.089474,1.0,1.016043,0.001413,inf
209,"(8, 10)",(2),0.100000,0.984211,0.100000,1.0,1.016043,0.001579,inf
215,"(9, 15)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
220,"(10, 11)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
224,"(10, 14)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
230,"(10, 15)",(2),0.094737,0.984211,0.094737,1.0,1.016043,0.001496,inf
297,"(3, 4, 5)",(2),0.163158,0.984211,0.163158,1.0,1.016043,0.002576,inf
300,"(3, 4, 6)",(2),0.142105,0.984211,0.142105,1.0,1.016043,0.002244,inf
304,"(3, 4, 7)",(2),0.094737,0.984211,0.094737,1.0,1.016043,0.001496,inf
307,"(8, 3, 4)",(2),0.115789,0.984211,0.115789,1.0,1.016043,0.001828,inf
316,"(9, 3, 4)",(2),0.089474,0.984211,0.089474,1.0,1.016043,0.001413,inf
328,"(10, 3, 4)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
330,"(3, 12, 4)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
333,"(3, 4, 14)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
338,"(3, 4, 15)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
340,"(16, 3, 4)",(2),0.078947,0.984211,0.078947,1.0,1.016043,0.001247,inf
347,"(3, 5, 14)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
368,"(3, 6, 7)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
376,"(10, 3, 6)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
379,"(10, 3, 7)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
388,"(8, 10, 3)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
403,"(4, 5, 6)",(2),0.121053,0.984211,0.121053,1.0,1.016043,0.001911,inf
416,"(4, 5, 7)",(2),0.084211,0.984211,0.084211,1.0,1.016043,0.001330,inf
428,"(16, 4, 5)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
443,"(10, 4, 6)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf
469,"(3, 4, 5, 6)",(2),0.073684,0.984211,0.073684,1.0,1.016043,0.001163,inf

In [ ]:
from apyori import apriori
store_data = pd.read_csv('store data.csv', header=None)

records = []
for i in range(0, 7501):
    records.append([str(store_data.values[i, j]) for j in range(0, 20)])
association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)
for item in association_results:
    pair = item[0]
    items = [x for x in pair]
    print('Rule: ' + items[0] + ' -> ' + items[1])
    print('Support: ' + str(item[1])) # Individual Popularity (ItemA/TotalTransactions)
    print('Confidence: ' + str(item[2][0][2])) #
    print('Lift: ' + str(item[2][0][3])) # How much It